# Generated by Django 5.0.6 on 2024-07-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_game_number_of_players_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_game_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
