# Generated by Django 5.0.6 on 2024-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_player_in_game_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['joined_at']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='in_game_id',
        ),
        migrations.AddField(
            model_name='player',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
