# Generated by Django 5.0.6 on 2024-08-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_player_options_remove_game_number_of_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
